language: php

php:
  - 8.0
  - 8.1
  - 8.2
  - 8.3

matrix:
    fast_finish: true
  
install:
  - composer install
  
script: phpunit -c tests/phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
  - composer global require scrutinizer/ocular
  - ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover